[package]
name = "grrs"
version = "0.1.0"
authors = ["Ganben <caozhao@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.2.10"
indicatif = "0.12.0"
log = "0.4.8"